# Generated by Django 5.2.12 on 2026-04-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidente',
            name='latitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='accidente',
            name='longitud',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
    ]
