# Generated by Django 5.2.12 on 2026-04-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormaTransito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('velocidad', 'Velocidad'), ('senales', 'Señales de tránsito'), ('alcoholemia', 'Alcoholemia'), ('peatones', 'Peatones'), ('motocicletas', 'Motocicletas'), ('documentos', 'Documentos'), ('infracciones', 'Infracciones'), ('general', 'General')], max_length=30, verbose_name='Categoría')),
                ('articulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Artículo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Norma de Tránsito',
                'verbose_name_plural': 'Normas de Tránsito',
                'ordering': ['categoria', 'titulo'],
            },
        ),
    ]
